# Generated by Django 4.2.5 on 2023-09-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_name', models.CharField(max_length=200)),
                ('send_email', models.CharField(max_length=200)),
                ('send_context', models.CharField(max_length=200)),
            ],
        ),
    ]
